# Git aliases
alias gs='git status --short'
alias gp='git push'
alias gpom='git push origin master'
alias gphm='git push heroku master'
alias ho='heroku open'
alias gpr='git pull --rebase'
alias glo='git log --oneline'
alias gdh='git diff HEAD'
alias gc='git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcom='git checkout master'
alias gb='git branch'
alias gsh='git stash save'
alias gsp='git stash pop'
