#!/usr/bin/env zsh
echo "Installing Homebrew, a good OS X package manager ..."
  ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  brew update
 
brew tap homebrew/dupes
brew install git zsh bash coreutils autoconf automake apple-gcc42 openssl mercurial macvim tmux reattach-to-user-namespace grc the_silver_searcher redis ack wget postgres --no-python 
brew update
brew doctor
