#!/usr/bin/env zsh

sudo -v

ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub | pbcopy
open https://github.com/account/ssh

# RBenv 
git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
rbenv install 1.9.3-p385
rbenv rehash
git clone https://github.com/sstephenson/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems

git clone git://github.com/altercation/solarized.git ~/Code/solarized

# Dotfiles
git clone https://github.com/kevinSuttle/dotfiles ~/Code/dotfiles
ln -s ~/Code/dotfiles/.hushlogin ~/.hushlogin
ln -s ~/Code/dotfiles/.inputrc ~/.inputrc
ln -s ~/Code/dotfiles/.screenrc ~/.screenrc
ln -s ~/Code/dotfiles/bash/.bashrc ~/.bashrc
ln -s ~/Code/dotfiles/git/.gitconfig ~/.gitconfig
ln -s ~/Code/dotfiles/git/.gitignore ~/.gitignore
ln -s ~/Code/dotfiles/ruby/.gemrc ~/.gemrc
ln -s ~/Code/dotfiles/vim/.vimrc ~/.vimrc
ln -s ~/Code/dotfiles/vim/.vim ~/.vim
ln -s ~/Code/dotfiles/vim/.gvimrc ~/.gvimrc
ln -s ~/Code/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/Code/dotfiles/zsh/.zshenv ~/.zshenv
ln -s ~/Code/dotfiles/ruby/default-gems ~/.rbenv/default-gems

cd ~/Code/dotfiles/
git submodule init
git submodule update

exec $SHELL -l